### ISSUE TITLE
Cosmological perturbations without the Boltzmann hierarchy

### ISSUE THREAD

**Issue by marius311** [xzackli/Bolt.jl#49]
Might be worth reading and potentially deciding this would be something that could make Bolt even cooler (or maybe a spinoff package): https://arxiv.org/abs/2105.02887

**Comment by jmsull** [comment]
I saw this as well and also thought it was a cool idea! Haven't had a chance to read the details yet but would definitely love to try it.

**Comment by jmsull** [comment]
I started to look at this again in detail - will open a new branch for it once #44 is merged.

**Comment by jmsull** [comment]
Started on this (finally) here #57 - will comment here once it is working "well".

**Comment by jmsull** [comment]
It works but is slow - this is good enough for me to close this issue. Follow the draft PR #57 for more!
