### ISSUE TITLE
Add reionization

### ISSUE THREAD

**Issue by jmsull** [xzackli/Bolt.jl#51]
As referenced in #41, we need to put reionization modeling in to get the correct sound speed and photon/baryon perturbations at low redshift. 

This does not look that complicated based on looking at [CAMB notes](https://cosmologist.info/notes/CAMB.pdf) section III.

**Comment by jmsull** [comment]
Added this in 43954ae - both Xe(x) and tau'(x) seem to agree at percent level with CLASS - the previous number of recfast redshifts (Nz=1000) was giving some numerical oscillations, and I bumped it up by a factor of 100 for the moment - though this should maybe be looked at some more.
<img width="509" alt="taup_reion_compare_raw" src="https://user-images.githubusercontent.com/50674574/133152519-4956c9ab-aac8-427a-8915-f5fe9ecc1074.png">
<img width="461" alt="taup_reion_compare" src="https://user-images.githubusercontent.com/50674574/133152522-62b74b89-3fb0-40dd-9199-30a0c5dac4af.png">
<img width="471" alt="xe_reion_compare_raw" src="https://user-images.githubusercontent.com/50674574/133152526-a49e3f5f-c982-4eb0-8916-679745f6aaa9.png">
<img width="459" alt="xe_reion_compare" src="https://user-images.githubusercontent.com/50674574/133152528-ebedaaca-0698-4c34-b800-9bfb2a726762.png">

When reionization is off there is some late-time disagreement in Xe that I haven't looked at, but it goes away when we use reionization, which we will always want to do.

I think CLASS does some smoothing of the RECFAST transitions but I haven't looked at that in detail.

**Comment by jmsull** [comment]
Should we close this for now and set up a separate issue to deal with smoothing transitions (i.e. also may want this for RSA?) as an enhancement?

**Comment by xzackli** [comment]
Is the smoothing of transitions important for RSA?

**Comment by jmsull** [comment]
This was so long ago that I am no longer sure exactly what I meant 😬, but I think the idea was that RSA uses \tau'' and c_{s,b} in the analytic [expression for the photon dipole perturbations](https://github.com/xzackli/Bolt.jl/blob/d610b2d501d8a0ebe476c841984702fb3c208c2c/src/perturbations.jl#L221), where this wiggling error around reionization could show up again (and may be worse for \tau'').

**Comment by xzackli** [comment]
> Should we close this for now and set up a separate issue to deal with smoothing transitions (i.e. also may want this for RSA?) as an enhancement?

Yes, I'm closing this! If we encounter issues with smoothness we can open a new issue.
