### ISSUE TITLE
why is RECFAST slow?

### ISSUE THREAD

**Issue by xzackli** [xzackli/Bolt.jl#71]
The RECFAST implementation currently in *Bolt* should be on the order of milliseconds. What's happening?

**Comment by jmsull** [comment]
A little follow up:

```julia
using Bolt
𝕡 = CosmoParams()
bg = Background(𝕡; x_grid=-20.0:0.01:0.0 nq=15)
𝕣 = Bolt.RECFAST(bg=bg, Yp=𝕡.Y_p, OmegaB=𝕡.Ω_b)
ih = IonizationHistory(𝕣, 𝕡, bg)

#  42.092 μs (245 allocations: 13.47 KiB)
@btime Bolt.RECFAST(bg=bg, Yp=𝕡.Y_p, OmegaB=𝕡.Ω_b)
# 6.547 s (67790063 allocations: 6.93 GiB)
@btime IonizationHistory(𝕣, 𝕡, bg)
```
and the flamegraph:

![Screen Shot 2022-09-13 at 15 49 09](https://user-images.githubusercontent.com/50674574/190022775-2e6b0624-ebb9-4014-a65a-5e852600078a.png)

**Comment by jmsull** [comment]
It looks like most of the solver time n the ionization odes is not actually in the stepping - it is in some dual-related stuff (first big block in the flamegraph). That is a lot of allocations - next step is probably to look at profiler applied to `ion_recfast!`.

**Comment by xzackli** [comment]
Yeah, I suspected as much. I actually have a more optimized version prototyped -- I was trying to do the integration the right way using events in OrdinaryDiffEq.jl ([gist](https://gist.github.com/xzackli/89e22b7e0bccbf3700c7e3c967d17a83)).

**Comment by jmsull** [comment]
Closing this since you merged the recfaster branch
